dist: trusty
sudo: false
language: node_js
node_js:
  - '10'
env:
  global:
    - CC_TEST_REPORTER_ID=bb5235628641cf3fc7ad9c20601a67f0853f69527cd22692528019de289bb83e
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - './node_modules'
install:
  - yarn install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - './cc-test-reporter before-build'
script:
  - ng test --no-watch --no-progress --codeCoverage --browsers=ChromeHeadlessCI
after_script:
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov'
# before_deploy:
#   - yarn global add netlify-cli
#   - ng build --prod
# deploy:
#   provider: script
#   script:
#     netlify deploy -s $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p --dir
#     ./dist/random-phone-number-generator
#   skip_cleanup: true
#   on:
#     branch: master
